/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'User' at '22/1/17 2:18 PM' with Gradle 2.14.1
 *
 * @author User, @date 22/1/17 2:18 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
